/**
 * Landing Page Generator
 * Creates optimized Next.js pages based on SEO content
 */

import { SEOContent } from './seoContentGenerator';
import fs from 'fs/promises';
import path from 'path';

class LandingPageGenerator {
  private pagesDir = path.join(process.cwd(), 'src', 'app', 'seo-pages');

  /**
   * Generate Next.js page from SEO content
   */
  async generatePage(content: SEOContent): Promise<{ success: boolean; path: string; url: string }> {
    try {
      // Ensure directory exists
      await this.ensureDirectory();

      // Generate page component
      const pageContent = this.generatePageComponent(content);

      // Write page file
      const pagePath = path.join(this.pagesDir, content.slug, 'page.tsx');
      await fs.mkdir(path.dirname(pagePath), { recursive: true });
      await fs.writeFile(pagePath, pageContent, 'utf-8');

      console.log(`Generated landing page: /seo-pages/${content.slug}`);

      return {
        success: true,
        path: pagePath,
        url: `/seo-pages/${content.slug}`,
      };
    } catch (error: unknown) {
      console.error(`Error generating page for ${content.slug}:`, error);
      throw error;
    }
  }

  /**
   * Generate multiple pages
   */
  async generatePages(contents: SEOContent[]): Promise<Array<{ success: boolean; path: string; url: string }>> {
    const results = [];

    for (const content of contents) {
      try {
        const result = await this.generatePage(content);
        results.push(result);
      } catch (error) {
        results.push({
          success: false,
          path: '',
          url: `/seo-pages/${content.slug}`,
        });
      }
    }

    return results;
  }

  /**
   * Ensure pages directory exists
   */
  private async ensureDirectory(): Promise<void> {
    try {
      await fs.access(this.pagesDir);
    } catch {
      await fs.mkdir(this.pagesDir, { recursive: true });
    }
  }

  /**
   * Generate page component code
   */
  private generatePageComponent(content: SEOContent): string {
    return `/**
 * SEO Landing Page: ${content.title}
 * Auto-generated by Marketing Automation Agent
 * Target Keyword: ${content.targetKeyword}
 */

import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: '${this.escapeString(content.title)} | Whole Lot of Nature',
  description: '${this.escapeString(content.metaDescription)}',
  keywords: ${JSON.stringify(content.keywords)},
  openGraph: {
    title: '${this.escapeString(content.title)}',
    description: '${this.escapeString(content.metaDescription)}',
    type: 'article',
  },
};

export default function ${this.generateComponentName(content.slug)}Page() {
  return (
    <div className="min-h-screen">
      {/* Breadcrumbs */}
      <div className="border-b border-white/10">
        <div className="max-w-6xl mx-auto px-4 py-3">
          <nav className="flex items-center space-x-2 text-sm">
            <Link href="/" className="text-[#66BB6A] hover:text-[#81C784]">
              Home
            </Link>
            <span className="text-white/40">/</span>
            <Link href="/seo-pages" className="text-[#66BB6A] hover:text-[#81C784]">
              Guides
            </Link>
            <span className="text-white/40">/</span>
            <span className="text-white/60">${this.escapeString(content.title)}</span>
          </nav>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-4 py-12">
        {/* Header */}
        <header className="mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-4 antialiased">
            ${this.escapeString(content.h1)}
          </h1>
          <p className="text-xl text-white/70 leading-relaxed">
            ${this.escapeString(content.metaDescription)}
          </p>
          <div className="flex flex-wrap gap-2 mt-6">
            ${content.keywords
              .slice(0, 5)
              .map(
                (kw) =>
                  `<span className="bg-[#2E7D32]/30 text-[#66BB6A] px-3 py-1 rounded-full text-sm font-semibold border border-[#66BB6A]/30">${kw}</span>`
              )
              .join('\n            ')}
          </div>
        </header>

        {/* Main Content */}
        <div className="grid lg:grid-cols-3 gap-8">
          {/* Content Column */}
          <div className="lg:col-span-2">
            <article className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-8 prose prose-lg prose-invert max-w-none">
              <div dangerouslySetInnerHTML={{ __html: \`${this.escapeBackticks(content.content)}\` }} />
            </article>

            {/* FAQs */}
            <div className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-8 mt-8">
              <h2 className="text-2xl font-bold text-white mb-6 antialiased">
                Frequently Asked Questions
              </h2>
              <div className="space-y-6">
                ${content.faqs
                  .map(
                    (faq) => `
                <div className="border-b border-white/10 pb-4">
                  <h3 className="text-lg font-semibold text-white mb-2 antialiased">
                    ${this.escapeString(faq.question)}
                  </h3>
                  <p className="text-white/70">
                    ${this.escapeString(faq.answer)}
                  </p>
                </div>`
                  )
                  .join('')}
              </div>
            </div>
          </div>

          {/* Sidebar */}
          <div className="lg:col-span-1">
            {/* CTA Box */}
            <div className="bg-gradient-to-br from-[#2E7D32] to-[#1B5E20] rounded-2xl p-6 text-white sticky top-4 border border-[#66BB6A]/30">
              <h3 className="text-2xl font-bold mb-4 antialiased">Shop Now</h3>
              <p className="mb-6 text-white/90">
                Explore our collection of premium plants, seeds, and gardening supplies.
              </p>
              <Link
                href="/shop"
                className="block w-full bg-white text-[#2E7D32] font-bold py-3 px-6 rounded-lg text-center hover:bg-white/90 transition-colors"
              >
                Browse Products
              </Link>
              <div className="mt-6 pt-6 border-t border-white/20">
                <p className="text-sm mb-4 text-white/80">Need expert advice?</p>
                <Link
                  href="/contact"
                  className="block w-full bg-white/10 hover:bg-white/20 text-white font-semibold py-2 px-4 rounded-lg text-center transition-colors border border-white/20"
                >
                  Contact Us
                </Link>
              </div>
            </div>

            {/* Related Links */}
            <div className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-6 mt-6">
              <h3 className="text-lg font-bold text-white mb-4 antialiased">
                Related Guides
              </h3>
              <ul className="space-y-3">
                ${content.internalLinks
                  .map(
                    (link) => `
                <li>
                  <Link href="${link}" className="text-[#66BB6A] hover:text-[#43A047] hover:underline">
                    ${this.getLinkText(link)}
                  </Link>
                </li>`
                  )
                  .join('')}
              </ul>
            </div>

            {/* Stats */}
            <div className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-6 mt-6">
              <h3 className="text-lg font-bold text-white mb-4 antialiased">
                Quick Facts
              </h3>
              <div className="space-y-4">
                <div className="flex justify-between items-center pb-3 border-b border-white/10">
                  <span className="text-white/60">Article Length</span>
                  <span className="font-bold text-[#66BB6A]">${content.wordCount} words</span>
                </div>
                <div className="flex justify-between items-center pb-3 border-b border-white/10">
                  <span className="text-white/60">Read Time</span>
                  <span className="font-bold text-[#66BB6A]">${Math.ceil(content.wordCount / 200)} min</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-white/60">Target Keywords</span>
                  <span className="font-bold text-[#66BB6A]">${content.keywords.length}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
`;
  }

  /**
   * Generate valid component name from slug
   */
  private generateComponentName(slug: string): string {
    return slug
      .split('-')
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join('');
  }

  /**
   * Escape string for JSX
   */
  private escapeString(str: string): string {
    return str.replace(/'/g, "\\'").replace(/"/g, '\\"');
  }

  /**
   * Escape backticks for template literals
   */
  private escapeBackticks(str: string): string {
    return str.replace(/`/g, '\\`').replace(/\$/g, '\\$');
  }

  /**
   * Get link text from URL
   */
  private getLinkText(url: string): string {
    const linkTexts: { [key: string]: string } = {
      '/shop': 'Browse All Products',
      '/shop/category/seeds': 'Shop Seeds',
      '/shop/category/fertilizers': 'Organic Fertilizers',
      '/blog': 'Gardening Blog',
      '/guides': 'Plant Care Guides',
      '/about': 'About Us',
    };

    return linkTexts[url] || url;
  }

  /**
   * List all generated pages
   */
  async listGeneratedPages(): Promise<string[]> {
    try {
      const entries = await fs.readdir(this.pagesDir, { withFileTypes: true });
      return entries.filter((entry) => entry.isDirectory()).map((entry) => entry.name);
    } catch {
      return [];
    }
  }
}

export default LandingPageGenerator;
